name: yakforward_brand
description: "assets and flutter widgets for Yakforward OÜ brand"
version: 1.0.0
homepage: www.yakforward.com

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.16.5"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^3.0.2

flutter:
  assets:
    - lib/logo.png
    - lib/icon.ttf
  fonts:
    - family: yakforward
      fonts:
        - asset: lib/icon.ttf
