name: brand
description: "icon for yakforward products"
version: 1.0.0
homepage: www.yakforward.com

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.16.5"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^3.0.1

flutter:
  assets:
    - lib/logo.png
  fonts:
    - family: yakforward
      fonts:
        - asset: lib/icon.ttf
